# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/lookup_map_mem/lookup_map_mem.xci
# IP: The module: 'lookup_map_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/lookup_map_mem/lookup_map_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lookup_map_mem'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/lookup_map_mem/lookup_map_mem.xci
# IP: The module: 'lookup_map_mem' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/lookup_map_mem/lookup_map_mem_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lookup_map_mem'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
