# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/rotate2rams_yuv420_fifo/rotate2rams_yuv420_fifo.xci
# IP: The module: 'rotate2rams_yuv420_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/rotate2rams_yuv420_fifo/rotate2rams_yuv420_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rotate2rams_yuv420_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/rotate2rams_yuv420_fifo/rotate2rams_yuv420_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rotate2rams_yuv420_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/rotate2rams_yuv420_fifo/rotate2rams_yuv420_fifo.xci
# IP: The module: 'rotate2rams_yuv420_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/rotate2rams_yuv420_fifo/rotate2rams_yuv420_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'rotate2rams_yuv420_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/lane/work/ubixum/prj/xenecor/src/lib/imager/rtl/ip/rotate2rams_yuv420_fifo/rotate2rams_yuv420_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rotate2rams_yuv420_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
